# Generated by Django 5.1.7 on 2025-04-02 06:21

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(upload_to='banner', verbose_name='Image')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='banner', verbose_name='Image 2 (optional)')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='banner', verbose_name='Image 3 (optional)')),
                ('img4', models.ImageField(blank=True, null=True, upload_to='banner', verbose_name='Image 4 (optional)')),
                ('img5', models.ImageField(blank=True, null=True, upload_to='banner', verbose_name='Image 5 (optional)')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, verbose_name=home.models.CategoryModel)),
                ('type', models.CharField(choices=[('platinum', 'platinum'), ('Gold', 'gold'), ('Silver', 'silver'), ('Bronze', 'bronze')], max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField()),
                ('show_order', models.IntegerField()),
                ('img1', models.ImageField(upload_to='images', verbose_name='Image')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Image 2 (optional)')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Image 3 (optional)')),
                ('img4', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Image 4 (optional)')),
                ('img5', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Image 5 (optional)')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
