# Generated by Django 5.1.7 on 2025-04-02 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_bannermodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannermodel',
            options={'verbose_name_plural': 'Banner'},
        ),
    ]
