# Generated by Django 5.1.7 on 2025-04-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_bannermodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productmodel',
            options={'ordering': ['show_order'], 'verbose_name': 'Available Products', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='show_order',
            field=models.IntegerField(default=10),
        ),
    ]
