# Generated by Django 5.1.7 on 2025-04-03 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_productmodel_weight_alter_productmodel_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold_1g', models.CharField(max_length=5, verbose_name='1gm gold price')),
                ('gold_8g', models.CharField(max_length=5, verbose_name='8gm gold price')),
                ('silver_1g', models.CharField(max_length=5, verbose_name='1gm silver price')),
            ],
            options={
                'verbose_name': 'Price Manager',
                'verbose_name_plural': 'Price list',
            },
        ),
    ]
