# Generated by Django 5.1.7 on 2025-04-05 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_goldprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldprice',
            name='gold_1g',
            field=models.CharField(max_length=15, verbose_name='1gm gold price'),
        ),
        migrations.AlterField(
            model_name='goldprice',
            name='gold_8g',
            field=models.CharField(max_length=15, verbose_name='8gm gold price'),
        ),
        migrations.AlterField(
            model_name='goldprice',
            name='silver_1g',
            field=models.CharField(max_length=15, verbose_name='1gm silver price'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='type',
            field=models.CharField(choices=[('Platinum', 'Platinum'), ('Gold', 'Gold'), ('Silver', 'Silver'), ('Diamond', 'Diamond')], max_length=50),
        ),
    ]
